from enum import Enum
from pydantic import BaseModel, Field


class RiskLevel(str, Enum):
    PROHIBITED = "prohibited"
    HIGH = "high_risk"
    LIMITED = "limited_risk"
    MINIMAL = "minimal_risk"
    UNCLEAR = "unclear"


class ArticleCitation(BaseModel):
    article: str = Field(description="e.g. 'Article 5(1)(a)' or 'Annex III, point 1'")
    summary: str = Field(description="What this provision establishes regarding the use case")


class ClassificationResult(BaseModel):
    use_case: str = Field(description="Original use case description")
    risk_level: RiskLevel
    confidence: str = Field(description="high / medium / low")
    primary_citations: list[ArticleCitation] = Field(
        description="Main legal basis for the classification"
    )
    reasoning: str = Field(description="Step-by-step legal reasoning")
    ambiguities: list[str] = Field(
        default_factory=list,
        description="Aspects that require human legal review",
    )
    disclaimer: str = Field(
        default=(
            "This output is generated by an automated system and does not constitute "
            "legal advice. Classification under the EU AI Act requires case-by-case "
            "assessment by qualified legal professionals."
        )
    )
